version: '2'

services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false' # disable auto creating topics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-startup-scripts:/opt/kafka/docker # new volume mapping
